spring:
  application:
    name: FreeCodeCampProject

  datasource:
    url: jdbc:postgresql://localhost:5432/FreeCodeCampDataBase
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      format_sql: true
    database: postgresql
    show-sql: true

logging:
  level:
    root: INFO
